[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmds = ["npm ci", "cd frontend && npm ci"]

[phases.build]
cmds = ["npm run build:studio", "cd frontend && npm run build"]

[start]
cmd = "node server.js"

